"""initial_media

Revision ID: 001_initial_media
Revises: 
Create Date: 2024-01-10 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_media'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table('meetings',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meetings_status_created', 'meetings', ['status', 'created_at'], unique=False)

    op.create_table('participants',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('meeting_id', sa.String(length=64), nullable=False),
        sa.Column('display_name', sa.String(length=128), nullable=False),
        sa.Column('role', sa.String(length=16), nullable=False),
        sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('client_meta', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='fk_participants_meeting'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participants_meeting_joined', 'participants', ['meeting_id', 'joined_at'], unique=False)

    op.create_table('chat_messages',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('meeting_id', sa.String(length=64), nullable=False),
        sa.Column('seq', sa.BigInteger(), nullable=False),
        sa.Column('sender_type', sa.String(length=16), nullable=False),
        sa.Column('sender_id', sa.String(length=64), nullable=True),
        sa.Column('message_type', sa.String(length=16), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('lang', sa.String(length=8), nullable=True),
        sa.Column('start_ms', sa.Integer(), nullable=True),
        sa.Column('end_ms', sa.Integer(), nullable=True),
        sa.Column('stt_meta', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='fk_chat_messages_meeting'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('meeting_id', 'seq', name='uq_meeting_seq')
    )
    op.create_index('idx_meeting_created', 'chat_messages', ['meeting_id', 'created_at'], unique=False)
    op.create_index('idx_meeting_sender_seq', 'chat_messages', ['meeting_id', 'sender_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index('idx_meeting_sender_seq', table_name='chat_messages')
    op.drop_index('idx_meeting_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_participants_meeting_joined', table_name='participants')
    op.drop_table('participants')
    op.drop_index('idx_meetings_status_created', table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
