"""update_schema_live_sessions_and_enums

Revision ID: 004
Revises: 003
Create Date: 2026-01-20 18:10:35.205646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create room_live_sessions (NEW)
    op.create_table('room_live_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_sessions_room_started', 'room_live_sessions', ['room_id', 'started_at'], unique=False)
    op.create_index('idx_live_sessions_room_status', 'room_live_sessions', ['room_id', 'status'], unique=False)
    op.create_index('idx_live_sessions_started_by', 'room_live_sessions', ['started_by'], unique=False)
    op.create_index('idx_live_sessions_status_started', 'room_live_sessions', ['status', 'started_at'], unique=False)

    # 2. Create room_live_session_members (NEW)
    op.create_table('room_live_session_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('client_meta', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['room_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['room_live_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_members_member', 'room_live_session_members', ['member_id'], unique=False)
    op.create_index('idx_session_members_room_session', 'room_live_session_members', ['room_id', 'session_id'], unique=False)
    op.create_index('idx_session_members_session', 'room_live_session_members', ['session_id'], unique=False)
    op.create_index('idx_session_members_session_joined', 'room_live_session_members', ['session_id', 'joined_at'], unique=False)
    op.create_index('idx_session_members_session_member', 'room_live_session_members', ['session_id', 'member_id'], unique=False)
    op.create_index('idx_session_members_user', 'room_live_session_members', ['user_id'], unique=False)

    # 3. Add mission indexes and cleanup (Optional but helpful if they don't conflict)
    # Note: Avoid operations on columns/indexes that already exist in 001
    
    # These indexes seem helpful and might not be in 001
    try:
        op.create_index('idx_room_sender_member', 'chat_messages', ['sender_member_id'], unique=False)
    except Exception:
        pass
        
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_live_session_members')
    op.drop_table('room_live_sessions')
    # ### end Alembic commands ###
