"""update_schema_live_sessions_and_enums

Revision ID: 3ce9c1b2b63e
Revises: 003
Create Date: 2026-01-20 18:10:35.205646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_live_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_sessions_room_started', 'room_live_sessions', ['room_id', 'started_at'], unique=False)
    op.create_index('idx_live_sessions_room_status', 'room_live_sessions', ['room_id', 'status'], unique=False)
    op.create_index('idx_live_sessions_started_by', 'room_live_sessions', ['started_by'], unique=False)
    op.create_index('idx_live_sessions_status_started', 'room_live_sessions', ['status', 'started_at'], unique=False)
    op.create_table('live',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['room_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'seq', name='uq_live_room_seq')
    )
    op.create_index('idx_live_member_seq', 'live', ['member_id', 'seq'], unique=False)
    op.create_index('idx_live_room_created', 'live', ['room_id', 'created_at'], unique=False)
    op.create_table('room_live_session_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('client_meta', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['room_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['room_live_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_members_member', 'room_live_session_members', ['member_id'], unique=False)
    op.create_index('idx_session_members_room_session', 'room_live_session_members', ['room_id', 'session_id'], unique=False)
    op.create_index('idx_session_members_session', 'room_live_session_members', ['session_id'], unique=False)
    op.create_index('idx_session_members_session_joined', 'room_live_session_members', ['session_id', 'joined_at'], unique=False)
    op.create_index('idx_session_members_session_member', 'room_live_session_members', ['session_id', 'member_id'], unique=False)
    op.create_index('idx_session_members_user', 'room_live_session_members', ['user_id'], unique=False)
    op.create_table('ai_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('source_live_id', sa.String(length=64), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('original_lang', sa.String(length=8), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('translated_lang', sa.String(length=8), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['source_live_id'], ['live.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'seq', name='uq_ai_room_seq')
    )
    op.create_index('idx_ai_room_created', 'ai_events', ['room_id', 'created_at'], unique=False)
    op.create_index('idx_ai_source_live', 'ai_events', ['source_live_id'], unique=False)
    # Adding tables with check if they exist (Manual check because Alembic create_table might fail)
    # Note: These tables were dropped manually in the previous step, so create_table is fine now.
    
    op.add_column('auth_tokens', sa.Column('session_id', sa.String(length=64), nullable=True))
    
    # Create new index before dropping old one to avoid foreign key errors in MySQL
    op.create_index('idx_auth_tokens_user_expires', 'auth_tokens', ['user_id', 'expires_at'], unique=False)
    
    # Use try-except or just avoid dropping if not sure, but here we try to be clean
    try:
        op.drop_index('idx_tokens_hash', table_name='auth_tokens')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_tokens_user_type', table_name='auth_tokens')
    except Exception:
        pass
        
    op.create_unique_constraint('uq_auth_tokens_token_hash', 'auth_tokens', ['token_hash'])
    
    try:
        op.drop_column('auth_tokens', 'scope')
    except Exception:
        pass
    try:
        op.drop_column('auth_tokens', 'last_used_at')
    except Exception:
        pass
    try:
        op.drop_column('auth_tokens', 'token_type')
    except Exception:
        pass

    op.create_index('idx_room_sender_member', 'chat_messages', ['sender_member_id'], unique=False)
    try:
        op.drop_index('idx_room_sender_seq', table_name='chat_messages')
    except Exception:
        pass
        
    op.create_index('idx_members_user', 'room_members', ['user_id'], unique=False)
    op.create_index('idx_rooms_created_by', 'rooms', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rooms_created_by', table_name='rooms')
    op.drop_index('idx_members_user', table_name='room_members')
    op.drop_index('idx_room_sender_member', table_name='chat_messages')
    op.create_index(op.f('idx_room_sender_seq'), 'chat_messages', ['room_id', 'sender_member_id', 'seq'], unique=False)
    op.add_column('auth_tokens', sa.Column('token_type', mysql.VARCHAR(length=16), nullable=False))
    op.add_column('auth_tokens', sa.Column('last_used_at', mysql.DATETIME(), nullable=True))
    op.add_column('auth_tokens', sa.Column('scope', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'auth_tokens', type_='unique')
    op.drop_index('idx_auth_tokens_user_expires', table_name='auth_tokens')
    op.create_index(op.f('idx_tokens_user_type'), 'auth_tokens', ['user_id', 'token_type', 'expires_at'], unique=False)
    op.create_index(op.f('idx_tokens_hash'), 'auth_tokens', ['token_hash'], unique=False)
    op.drop_column('auth_tokens', 'session_id')
    op.drop_index('idx_ai_source_live', table_name='ai_events')
    op.drop_index('idx_ai_room_created', table_name='ai_events')
    op.drop_table('ai_events')
    op.drop_index('idx_session_members_user', table_name='room_live_session_members')
    op.drop_index('idx_session_members_session_member', table_name='room_live_session_members')
    op.drop_index('idx_session_members_session_joined', table_name='room_live_session_members')
    op.drop_index('idx_session_members_session', table_name='room_live_session_members')
    op.drop_index('idx_session_members_room_session', table_name='room_live_session_members')
    op.drop_index('idx_session_members_member', table_name='room_live_session_members')
    op.drop_table('room_live_session_members')
    op.drop_index('idx_live_room_created', table_name='live')
    op.drop_index('idx_live_member_seq', table_name='live')
    op.drop_table('live')
    op.drop_index('idx_live_sessions_status_started', table_name='room_live_sessions')
    op.drop_index('idx_live_sessions_started_by', table_name='room_live_sessions')
    op.drop_index('idx_live_sessions_room_status', table_name='room_live_sessions')
    op.drop_index('idx_live_sessions_room_started', table_name='room_live_sessions')
    op.drop_table('room_live_sessions')
    # ### end Alembic commands ###
