"""Add_RoomInvitation

Revision ID: 009
Revises: 008
Create Date: 2026-02-01 12:37:01.659686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009'
down_revision: Union[str, None] = '008_add_chat_msg_trans_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_invitations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('inviter_id', sa.String(length=64), nullable=False),
    sa.Column('invitee_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_invitations_invitee_status', 'room_invitations', ['invitee_id', 'status'], unique=False)
    op.create_index('idx_room_invitations_room', 'room_invitations', ['room_id'], unique=False)
    op.create_index('idx_room_invitations_room_invitee', 'room_invitations', ['room_id', 'invitee_id'], unique=False)
    op.drop_index(op.f('idx_room_sender_seq'), table_name='chat_messages')
    op.create_index('idx_members_user', 'room_members', ['user_id'], unique=False)
    op.create_index('idx_rooms_created_by', 'rooms', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rooms_created_by', table_name='rooms')
    op.drop_index('idx_members_user', table_name='room_members')
    op.create_index(op.f('idx_room_sender_seq'), 'chat_messages', ['room_id', 'sender_member_id', 'seq'], unique=False)
    op.drop_index('idx_room_invitations_room_invitee', table_name='room_invitations')
    op.drop_index('idx_room_invitations_room', table_name='room_invitations')
    op.drop_index('idx_room_invitations_invitee_status', table_name='room_invitations')
    op.drop_table('room_invitations')
    # ### end Alembic commands ###
